export const _Area = {
    BanjaraHills: "Banjara Hills",
    JubileeHills: "Jubilee Hills",
    Gachibowli: "Gachibowli",
    FinancialDistrict: "Financial District",
    Nanakramguda: "Nanakramguda",
    Kokapet: "Kokapet",
    Manikonda: "Manikonda",
    Kondapur: "Kondapur",
    Madhapur: "Madhapur",
    HitechCity: "Hitech City",
    Miyapur: "Miyapur",
    Chandanagar: "Chandanagar",
    Nallagandla: "Nallagandla",
    Nizampet: "Nizampet",
    Kukatpally: "Kukatpally",
    Bowenpally: "Bowenpally",
    Suchitra: "Suchitra",
    Uppal: "Uppal",
    Nagole: "Nagole",
    Alkapur: "Alkapur",
    Tellapur: "Tellapur",
    Patancheru: "Patancheru",
    Bachupally: "Bachupally",
    Adibatla: "Adibatla(near Aerospace SEZ)",
    Shamshabad: "Shamshabad(near Airport)",
    SrisailamHighwayBelt: "Srisailam Highway belt",
    Pocharam: "Pocharam",
    Maheshwaram: "Maheshwaram",
    Tukkuguda: "Tukkuguda",
    Puppalaguda: "Puppalaguda",
    LBNagar: "LB Nagar",
    OsmanNagar: "Osman Nagar",
    Gandipet: "Gandipet",
    Mokila: "Mokila",
    PatancheruOutskirts: "Patancheru outskirts",
    NeoPolisFinancialDistrict: "NeoPolis, Financial District",
    Begumpet: "Begumpet",
    Ameerpet: "Ameerpet",
    Secunderabad: "Secunderabad",
    Somajiguda: "Somajiguda",
    Kollur: "Kollur",
    Nandigaon: "Nandigaon",
    kardanpur: "kardanpur",
    velimala: "velimala",
    beeramguda: "Beeramguda",
    Shankarpalle: "Shankarpalle"
}